SELECT TBL.CONTINENT, FLOOR(AVG(TBL.POPULATION))
FROM
(
    SELECT COUNTRY.CONTINENT, CITY.POPULATION
    FROM CITY
    INNER JOIN COUNTRY
    ON CITY.COUNTRYCODE = COUNTRY.CODE
    WHERE COUNTRY.CONTINENT IS NOT NULL
) TBL
GROUP BY TBL.CONTINENT
ORDER BY AVG(TBL.POPULATION) ASC
